# Generated by Django 4.1.1 on 2022-09-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlehistory",
            name="duplicates",
            field=models.BooleanField(
                default=False, verbose_name="Allow duplicate letters"
            ),
        ),
        migrations.AlterField(
            model_name="wordlehistory",
            name="length",
            field=models.IntegerField(default=5, verbose_name="Word length"),
        ),
        migrations.AlterField(
            model_name="wordlehistory",
            name="tries",
            field=models.IntegerField(default=6, verbose_name="Guesses allowed"),
        ),
    ]
